version: '3.8'

services:
  app:
    image: marchenw/qml_image:1.3
    container_name: qml
    ipc: host
    ports:
      - 8888:8888
    volumes:
      - ./:/var/
    working_dir: /var/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    stdin_open: true # docker run -i
    tty: true # docker run -t
