log:
  model_name: Simple_QHN
  project_name: QML-MNIST
  val_log_freq_epoch: 1
  epoch: 100
  n_fold: 5
  dry_run: false
  device:
    gpu:
      - 0
  log_path: Logs
  checkpoint_path: Checkpoints
  precision: 32

loader:
  train:
    batch_size: 32
    num_workers: 8
    pin_memory: True
    shuffle: True
  eval:
    batch_size: 1000
    num_workers: 8
    pin_memory: False
    shuffle: False
  

data:
  path: Data/preprocessed/all

network:
  model: ${log.model_name}
  num_classes: 2
  encoder: ${SCCNN_bn}
  attention: ${Attention}
  LSTM: ${LSTM}
  decoder: ${Decoder}
  is_encoder_shared: True
  encoderType: SCCNN_bn
  Simple_QHN: ${Simple_QHN}
  hybrid: ${quantum_circuit}

optimizer:
  optimizer: Adam
  lr: 1e-5


runner: OneSiteHoldout_Runner

