log:
  model_name: Simple_QHN
  project_name: QML-MNIST
  val_log_freq_epoch: 1
  epoch: 100
  n_fold: 5
  dry_run: false
  device:
    gpu:
      - 0
  log_path: Logs
  checkpoint_path: Checkpoints
  precision: 32

loader:
  train:
    batch_size: 32
    num_workers: 8
    pin_memory: True
    shuffle: True
  eval:
    batch_size: 1000
    num_workers: 8
    pin_memory: False
    shuffle: False
  

data:
  path: Data/preprocessed/all
  same_size: True
  site: ["KKI", "NI", "NYU", "OHSU", "Peking"]

network:
  model: ${log.model_name}
  num_classes: 2
  LSTM: ${LSTM}
  Simple_QHN: ${Simple_QHN}

optimizer:
  optimizer: Adam
  lr: 1e-4


