
LSTM:
  input_size: 116
  hidden_size: 128
  num_layers: 1
  bidirectional: True

Simple_QHN:
  n_qubits: 2
  shift: 0.6
  lstm_hidden: 128
  linear_out: 64
  backend: aer_simulator


quantum_circuit:
  n_qubits: 3
  simulator: aer_simulator
  shift: 0.5
  shots: 100
  dense_type: 2