
LSTM:
  input_size: ${SCCNN.conv_block4.out_f}
  hidden_size: 128
  num_layers: 1
  bidirectional: True

Simple_QHN:
  n_qubits: 2
  shift: 0.6
  is_cnot: True
  lstm_hidden: 128
  linear_out: 64


quantum_circuit:
  n_qubits: 3
  simulator: aer_simulator
  shift: 0.5
  shots: 100
  is_cnot: True
  dense_type: 2