
LSTM:
  input_size: 116
  hidden_size: 128
  num_layers: 1
  bidirectional: True

Simple_QHN:
  n_qubits: 4
  shift: 0.6
  shots: 200
  lstm_hidden: 128
  linear_out: 64
  backend: aer_simulator
  no_quantum: False
  model: model_7

